name: Secret scan

on: [push, pull_request]

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create "exclude path" configuration file
        run: echo 'package-lock.json' > exclude.txt

      - uses: max/secret-scan@master
        with:
          exclude_path: 'exclude.txt'
