name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '30 09 * * *'

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-verdsions: [ '15.x', '16.x', '17.x' ]
        steps:
            - name: Clone and checkout branch
              uses: actions/checkout@v1

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: make deps

            - name: Run tests
              run: make test

            - name: Build project
              run: make
